language: cpp
dist: bionic
compiler:
  - gcc

install:
  - sudo apt update
  - sudo apt install -y g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo apt install -y cmake
  - if [ $TRAVIS_OS_NAME = "linux" ]; then
      sudo bash .travis/install_eigen3.sh;
      sudo bash .travis/install_ceres_solver200.sh;
      sudo bash .travis/install_opencv451.sh;
      sudo bash .travis/install_intel_opencl.sh;
    fi;
  - sudo apt install -y libcgal-dev

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=RELWITHDEBINFO -DCeres_DIR=/opt/ceres-solver200 ..
  - make -j12
  - cd ..
#   - ./build/test_mesh_min_cut
